### ISSUE TITLE
Issues in codeblocks.

### ISSUE THREAD

**Issue by tawandamahanzu** [DenisROBERT1/Loebner-bot-sample#1]
couldn't compile file as is. noted issues: use of strncpy_s which seems to be unsupported outside visual CPP.

**Comment by DenisROBERT1** [comment]
I have modified the file WebSocket.h

**Comment by tawandamahanzu** [comment]
Thanks, that's great work there. I finally managed to get working though
there some issue with disconnection. Opened a new issue. Will probably be
using your interface to enter this year.

Thanks for the app.
