### ISSUE TITLE
Disconnection problem

### ISSUE THREAD

**Issue by tawandamahanzu** [DenisROBERT1/Loebner-bot-sample#2]
Hi there. Thanks again for the interface ,finally got it to work. Just noticed two issues

1 The App disconnects during execution with a " no reason " or "due to bad ping". This is happens every less than a minute into the connection sometimes.

2 Sometimes after disconnection if reconnected the Appp will not show a response in the judge program even though the app itself receives input and shows both input and output in it's own window.

Not sure if the whether the issue is within the LLP2 or the App or a combination.

Thanks in advance for the solution. Will probably be using the App myself.

**Comment by tawandamahanzu** [comment]
Was using Firefox for the lpp2  controller and clients

**Comment by DenisROBERT1** [comment]
Can't reproduce the bug, with code::block 13.12 and Firefox 60.0.1

- Have you the last version of programs ?
- Have you rebuilt the project ?
- Can you activate traces and send them here, please ?

Thanks

**Comment by tawandamahanzu** [comment]
Thanks for the reply let me try to do all that and respond ASAP.

**Comment by tawandamahanzu** [comment]
Hello, I updated browser to latest 60.0.1 since last time
Using Code::Blocks 16.01
Also tried redownloaded all LPP2 files as well as loebnerbot app files.
Still having the same issue.

Please advise on how to activate traces and where to get the traces from
once activated (i.e.the directory or output screen.)

I tried uncommenting The //#ifdef TRACE 1 line but don't seam to get any
doc labelled logxxxx.tmp on my system anywhere.

Thanks.

**Comment by DenisROBERT1** [comment]
To activate traces, you just have to uncomment the line "// #define TRACE 1", compile the project and run it. A log file should be created in the temporary folder. To know where is this temporary folder, type "echo %TEMP%" in a cmd window.

**Comment by tawandamahanzu** [comment]
Hello took the log file after disconnection. Here it is :


---------- CLIENT ----------
GET /socket.io/?EIO=3&transport=polling&t=BUmvGn HTTP/1.1
Accept: */*
Accept-Language: en-EN
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like
Gecko
Host: 127.0.0.1:8080
DNT: 1
Connection: Keep-Alive
Cookie: io=pTzblLqqYY3Vn6w5AAAm


---------- SERVER ----------
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 103
Access-Control-Allow-Origin: *
X-XSS-Protection: 0
Set-Cookie: io=c1czbcE_6VQ4tk56AAAD; Path=/; HttpOnly
Date: Sat, 02 Jun 2018 11:11:19 GMT
Connection: keep-alive

96:0{"sid":"c1czbcE_6VQ4tk56AAAD","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}2:40
---------- CLIENT ----------
GET /socket.io/?EIO=3&transport=websocket&sid=c1czbcE_6VQ4tk56AAAD HTTP/1.1
Origin: null
Sec-WebSocket-Key: AJAxz5V6WeXSvyzbtYNNAw==
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like
Gecko
Host: 127.0.0.1:8080
DNT: 1
Connection: Upgrade
Upgrade: Websocket
Cache-Control: no-cache
Cookie: io=c1czbcE_6VQ4tk56AAAD


---------- SERVER ----------
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: kAwW+2aVwI/YYUoVwSe0Zlg+9mI=


---------- CLIENT ----------
8186175D252A252D57457538
OpCode = 1 masked 2probe

---------- SERVER ----------
81063370726F6265
OpCode = 1 not masked 3probe

---------- CLIENT ----------
8181FD721E01C8
OpCode = 1 masked 5

---------- CLIENT ----------
81CE026088923652D3B0610FE6E6700FE4B02E42F3CE2013FCF37615FBCE205AD4B07005EFFB7114EDE05E42A4CE2009ECCE205AD4B06309B8CE204CD4B07105EBE06714D4B0383CAAF36003B9A0313CAAEF203D
OpCode = 1 masked
42["control","{\"status\":\"register\",\"id\":\"ai0\",\"secret\":\"abc123\"}"]

---------- CLIENT ----------
81D69A9B2AA9AEA9718BF9F444DDE8F4468BB6B951F5B8E85EC8EEEE59F5B8A1768BE8F45FC7FED244CFF5E947C8EEF245C7C6B906F5B8F24EF5B8A1768BFBF21AF5B8B7768BE9FE49DBFFEF768BA0C708C8F8F81B9BA9C708D4B8C6
OpCode = 1 masked
42["control","{\"status\":\"roundInformation\",\"id\":\"ai0\",\"secret\":\"abc123\"}"]

---------- SERVER ----------
815734325B22726F756E64496E666F726D6174696F6E222C227B5C22726F756E644E756D6265725C223A2D312C205C227374617475735C223A5C2246696E69736865645C222C205C22706172746E6572735C223A7B7D7D225D
OpCode = 1 not masked 42["roundInformation","{\"roundNumber\":-1,
\"status\":\"Finished\", \"partners\":{}}"]

---------- CLIENT ----------
8181735A0E9B41
OpCode = 1 masked 2

---------- SERVER ----------
810133
OpCode = 1 not masked 3

---------- CLIENT ----------
8181C8CD854DFA
OpCode = 1 masked 2

---------- SERVER ----------
8800
OpCode = 8 not masked

**Comment by tawandamahanzu** [comment]
To give a better description of the big
On my part I have run the server and have judge0 and conf0 connected as
shown in controller.

After compiling and executing the Bot everything works fine until after at
most 49 seconds after running then there is popup messege 1:title: "Web
socket disconnection" and body: "Unknown reason."


Immediately after is message2: title:"Web Socket error" and body: " Error
in function OnConnect : Bad response to ping" .

The interface Start  is enabled.

**Comment by DenisROBERT1** [comment]
Hello,
I have changed the ping delay, because it seems you have a max delay of 25000 milliseconds when the default value for me was greater than 30 seconds. Please reload the new programs and tell me if you always have the bug. Thanks.

**Comment by tawandamahanzu** [comment]
OK thanks let me try that.

**Comment by tawandamahanzu** [comment]
The interface works great now, thanks. No disconnection at all now.
